version: "3.7"
services:   
  dota-server:
    build:
      context: ./backend/
    container_name: dota-backend
    ports:
      - 4000:4000
  dota-client:
    container_name: dota-client
    command: yarn dev
    image: nuxt_dev
    build:
      context: ./frontend/
    ports:
      - 3000:3000
